dist: trusty
sudo: false

language: c
compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - autoconf
            - automake
            - make
            - xsltproc
            # Workaround
            - libaprutil1-dev
            #- uuid-dev
            - libglib2.0-dev
            - gnome-icon-theme-extras
            - gnome-icon-theme-symbolic
            - sound-theme-freedesktop
            - pidgin-data
before_script:
    - mkdir -p m4
    - autoreconf -fiv
    - ./configure --disable-silent-rules
script:
    - make check
after_failure:
    - cat test-suite.log


notifications:
    email: false
