dist: trusty
sudo: required

language: c
compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - autoconf
            - automake
            - make
            - xsltproc
            - uuid-dev
            - libglib2.0-dev
before_script:
    - mkdir -p m4
    - autoreconf -fiv
    - ./configure --disable-silent-rules
script:
    - make check 
    # For now we cannot run tests as Travis Trusty env lacks IPv6 support
after_failure:
    - cat test-suite.log


notifications:
    email: false
