dist: trusty
sudo: false

language: c
compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            # Workaround
            - libaprutil1-dev
            #- uuid-dev
            - libglib2.0-dev
            - gnome-icon-theme-extras
            - gnome-icon-theme-symbolic
            - sound-theme-freedesktop
            - pidgin-data
install:
    - pip3 install meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - unzip ninja-linux.zip
    - export PATH=$(pwd):$PATH

before_script:
    - meson build -Db_coverage=true
script:
    - ninja -C build -v test
    - cat build/meson-logs/testlog.txt
after_success:
    - bash <(curl -s https://codecov.io/bash)


notifications:
    email: false
